// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
     return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? 'AIzaSyCzMGuLO0bMuC5nMiWF1DQK_3hc1xePh5s',
      appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '1:568002325053:android:c5a5d0b6d733ed02b01854',
      messagingSenderId: dotenv.env['FIREBASE_ANDROID_MESSAGING_SENDER_ID'] ?? '568002325053',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'gitlauk-e752f',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'gitlauk-e752f.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyAfOpa7eAQRHVLRwb2TLdkcvutNA3EPqcI',
      appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:568002325053:ios:262d2fbb82561459b01854',
      messagingSenderId: dotenv.env['FIREBASE_IOS_MESSAGING_SENDER_ID'] ?? '568002325053',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'gitlauk-e752f',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'gitlauk-e752f.firebasestorage.app',
      iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.example.flutterApplication1',
    );
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'AIzaSyCOtOZmZU_8nhg7RF5C5LW7cq-dpOVr-P4',
      authDomain: dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ?? 'gitlauk-e752f.firebaseapp.com',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'gitlauk-e752f',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'gitlauk-e752f.firebasestorage.app',
      messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '568002325053',
      appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '1:568002325053:web:d7c078cff8a6e507b01854',
      measurementId: dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'] ?? 'G-KVDNB8S399',
    );
  }
}